"""Added event description to Event model

Revision ID: f40142f37a22
Revises: 6832f7a019c1
Create Date: 2025-03-29 19:34:13.426739

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f40142f37a22'
down_revision = '6832f7a019c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_description', sa.Text(), nullable=True))
        batch_op.alter_column('event_location',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.alter_column('event_location',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.drop_column('event_description')

    # ### end Alembic commands ###
